apiVersion: couchbase.com/v1
kind: CouchbaseCluster
metadata:
  name: cb-eks-demo
spec:
  baseImage: couchbase/server
  version: enterprise-5.5.3
  authSecret: cb-example-auth
  exposeAdminConsole: true
  adminConsoleServices:
    - data
  exposedFeatures:
    - xdcr
  cluster:
    dataServiceMemoryQuota: 1024
    indexServiceMemoryQuota: 1024
    searchServiceMemoryQuota: 1024
    eventingServiceMemoryQuota: 1024
    analyticsServiceMemoryQuota: 1024
    indexStorageSetting: plasma
    autoFailoverTimeout: 10
    autoFailoverMaxCount: 3
    autoFailoverOnDataDiskIssues: true
    autoFailoverOnDataDiskIssuesTimePeriod: 120
    autoFailoverServerGroup: false
  buckets:
    - name: default
      type: couchbase
      memoryQuota: 128
      replicas: 1
      ioPriority: high
      evictionPolicy: valueOnly
      conflictResolution: seqno
      enableFlush: true
      enableIndexReplica: false
  servers:
    - name: data-east-1a 
      size: 1
      services:
        - data
      serverGroups:
       - us-east-1a
      pod:
        volumeMounts:
          default: pvc-us-east-1a 	# /opt/couchbase/var/lib/couchbase
          data: pvc-us-east-1a	# /mnt/data
    - name: data-east-1b
      size: 1
      services:
        - data
      serverGroups:
       - us-east-1b
      pod:
        volumeMounts:
          default: pvc-us-east-1b
          data: pvc-us-east-1b
    - name: data-east-1c
      size: 1
      services:
        - data
      serverGroups:
       - us-east-1c
      pod:
        volumeMounts:
          default: pvc-us-east-1c
          data: pvc-us-east-1c
    - name: query-east-1b
      size: 1
      services:
        - query
        - index
      serverGroups:
       - us-east-1b
      pod:
        volumeMounts:
          default: pvc-us-east-1b
          index: pvc-us-east-1b
    - name: query-east-1c
      size: 1
      services:
        - index
        - query
      serverGroups:
       - us-east-1c
      pod:
        volumeMounts:
          default: pvc-us-east-1c
          index: pvc-us-east-1c
  securityContext:
    fsGroup: 1000
  volumeClaimTemplates:
    - metadata:
        name: pvc-us-east-1a
      spec:
        storageClassName: "sc-us-east-1a"
        resources:
          requests:
            storage: 5Gi
    - metadata:
        name: pvc-us-east-1b
      spec:
        storageClassName: "sc-us-east-1b"
        resources:
          requests:
            storage: 5Gi
    - metadata:
        name: pvc-us-east-1c
      spec:
        storageClassName: "sc-us-east-1c"
        resources:
          requests:
            storage: 5Gi
