apiVersion: couchbase.com/v1
kind: CouchbaseCluster
metadata:
  name: cb-eks-demo
spec:
  baseImage: couchbase/server
  version: enterprise-5.5.3
  authSecret: cb-example-auth
  exposeAdminConsole: true
  adminConsoleServices:
    - data
  exposedFeatures:
    - xdcr
  cluster:
    dataServiceMemoryQuota: 256
    indexServiceMemoryQuota: 256
    searchServiceMemoryQuota: 256
    eventingServiceMemoryQuota: 256
    analyticsServiceMemoryQuota: 1024
    indexStorageSetting: memory_optimized
    autoFailoverTimeout: 10
    autoFailoverMaxCount: 3
    autoFailoverOnDataDiskIssues: true
    autoFailoverOnDataDiskIssuesTimePeriod: 120
    autoFailoverServerGroup: false
  serverGroups:
    - us-east-1a
    - us-east-1b
    - us-east-1c
  buckets:
    - name: default
      type: couchbase
      memoryQuota: 128
      replicas: 1
      ioPriority: high
      evictionPolicy: valueOnly
      conflictResolution: seqno
      enableFlush: true
      enableIndexReplica: false
  servers:
    - size: 5 
      name: data 
      services:
        - data
    - size: 3
      name: query
      services:
        - query
        - index
      serverGroups:
        - us-east-1b
        - us-east-1c
  securityContext:
    fsGroup: 1000
