apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  labels:
    k8s-addon: storage-aws.addons.k8s.io
  name: sc-us-east-1b
parameters:
  type: gp2
  zone: us-east-1b
provisioner: kubernetes.io/aws-ebs
reclaimPolicy: Delete
